command /sb-skill-dungeon:
	trigger:
		open virtual chest inventory with size 4 named "Dungeoneering" to player
		format gui slot (integers between 0 and 35) of player with {Menu-Panes}
		format gui slot 31 of player with {Menu-Close} to close
		format gui slot 30 of player with {Menu-GoBack} to run:
			make player execute command "/sb-skills"
		format gui slot 12 and 14 of player with red stained glass pane named "&cSOON"
		format gui slot 13 of player with wither skeleton skull named "&cCatacomb Lv%{catacomb.%UUID of player%}%" with lore "&7Complete dungeons floor to gain" and "&7catacombs experiences." and "&7" and "&dItem Stat Boost: +%{Catacomb-ItemStatBoost.%UUID of player%}%&d%%" and "&7" and "&eClick to view!"
		